version = 0.1
[default.deploy.parameters]
stack_name = "portable-lambda-zip"
resolve_s3 = true
s3_prefix = "portable-lambda-zip"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\""
